### ISSUE TITLE
Alf Shatterer not mining

### ISSUE THREAD

**Issue by spongario** [noeppi-noeppi/MythicBotany#13] opened 2020-11-19 23:57 UTC
When trying to mine with the Alf Shatterer, it sometimes does not mine at all. Happens with every block

https://puu.sh/GPgya/0d1d84b839.gif

1.16.4 ATM6 , using mythicbotany 1.16.3-1.16.6 jar

**Comment by abint** [comment] 2020-11-21 02:24
Its an issue with the mana being constantly updated and your held item being updated/changed. If you have a band of aura or full alf/terrasteel armour, this can happen. A temporary solution I've come up with while this bug gets patched is have a band of mana in your hotbar. It'll take priority for the mana generation, letting you use your alf shatterer

**Comment by noeppi-noeppi** [comment] 2020-11-28 09:05
Might be a duplicate of #8. The version you wrote in your issue does not exist. Please clarify what version you're using and test it with the latest version. Thanks

**Comment by noeppi-noeppi** [comment] 2020-12-25 19:17
I'm going to close this now as there was no action a long time. If the issue still persists, feel free to reopen it.

**Closed by noeppi-noeppi** 2020-12-25 19:17 UTC
Labels: question
