### ISSUE TITLE
Mining w/ Terra Shatterer & Greatest Band of Aura Equipped not possible

### ISSUE THREAD

**Issue by FakeGrimes** [noeppi-noeppi/MythicBotany#11] opened 2020-11-12 19:20 UTC
Version: MythicBotany-1.16.3-1.1.3
As title stated when Equipped with the Greatest Band of Aura I can not mine any blocks With a Terra Shatterer. 
Unequipping the Band or using the Botany default Greater Band of Aura works fine.

Video Demonstration: https://www.youtube.com/watch?v=2Mub1Rzg91I

**Comment by noeppi-noeppi** [comment] 2020-11-12 19:20
Duplicate of #8

**Closed by noeppi-noeppi** 2020-11-12 19:20 UTC
Labels: duplicate
