### ISSUE TITLE
Alfsteel mana cost misleading

### ISSUE THREAD

**Issue by Bastian-5** [noeppi-noeppi/MythicBotany#56] opened 2021-06-02 10:04 UTC
There is very little telling you that the alfsteel cost is 2 mana pools. This cost me 1.8 mana pools because the items despawned. FIX THIS NOW. 
How:
Change the default 1x scale to .5x scale on that page, showing that the terasteel is 1/4th the cost of alfsteel
Change "much more mana" to "4x as much mana"
add a second bar to each page on that section, showing the terrasteel to only have half of one bar, whereas alfsteel fills up both bars.

The fact I had to find this out by wasting 1.8 pools of mana means you really should have had other botania players look at it, and watched them try to figure it out. I'm sure many of them would have tried to make alfsteel with only 1 mana pool, especially since you gated the gaia fights behind alfsteel, pushing it from "around the time you'd fight gaia" to strictly "before you fight gaia". If anything I have said is untrue, especially if it fixes addresses the main issue at hand, please find a way to slap the people who amalgamated the Direwolf 20 modpack, as that is where I encountered this.

**Comment by noeppi-noeppi** [comment] 2021-06-02 12:36
This is a duplicate of #28. If you want to contribute to the issue, please comment there.


 > FIX THIS NOW.

I create mods because I like to create mods and not because I have to do anything to these. So it is my decision what I fix and what not. And I don't like people who come here and tell me in a rude way that I have to fix something because clearly I don't have to fix something. Nothing even stops me from making it worse.

So please mind your language and write something like `I'd appreciate if you could fix this.` Thanks

 > How:
 > ...

As said above, its my decision what I do with the mod. You can make suggestions and/or requests. So it would be better if you wrote `my suggestions for this problem would be`.

 > you really should have had other botania players look at it, and watched them try to figure it out. I'm sure many of them would have tried to make alfsteel with only 1 mana pool

I have watched many videos about this mod that are available on youtube and I know that it has been a little bit unclear. But all I have seen is that people hav tried to make their first alfsteel with two pools and then could not instantly create the second. So they did not lose any mana. And even if they did: It is a game and you should be thankful that people create mods for you to play with instead of telling the mod authors what they have to do.

Also I want to point out that in the latest version it is pretty clear, what the mana cost are:

![Bildschirmfoto 2021-06-02 14:32:51](https://user-images.githubusercontent.com/63002502/120480548-74ba6d80-c3af-11eb-852a-d667244d1d6f.png)

It clearly reads `0.25x Zoom` when hovered.

**Closed by noeppi-noeppi** 2021-06-02 12:36 UTC
