### ISSUE TITLE
MythicBotany not showing in Lexica Botania (Direwolf20)

### ISSUE THREAD

**Issue by Aneres0203** [noeppi-noeppi/MythicBotany#112] opened 2022-07-07 14:51 UTC
So, a previous version of Direwolf20 had the lexica filled with the Mythic Botany chapters and now they don't show up. Using version 1.6.1

**Comment by noeppi-noeppi** [comment] 2022-07-08 18:43
Duplicate of #111

**Closed by noeppi-noeppi** 2022-07-08 18:43 UTC
