### ISSUE TITLE
Ticking Entity Crashes in both Botania and MythicBotany

### ISSUE THREAD

**Issue by thelapisfox** [noeppi-noeppi/MythicBotany#41] opened 2021-05-02 12:28 UTC
This is not my first crash of this type. I have also crashed about 6 other times and each of those times had something to do with Botania, 3 times was the red string container, and once it was the alfheim portal. This time, the erroring entity is the raindeletia.

Minecraft 1.16.5
MB: 1.2.10
Bot: 415
Forge: 36.1.4

https://paste.ee/p/9CwDG

**Comment by noeppi-noeppi** [comment] 2021-05-02 16:34
My guess would be it's the Performant mod. But as performant is closed source, I can not check their code to verify it.
Thant means I'll not work on this if you can not reproduce it without the Performant mod.
So either try to reproduce it without Performant or post it on their issue tracker stating that it might be their fault and they should check it themselves as thy have access to their code which I haven't.

**Comment by noeppi-noeppi** [comment] 2021-05-10 07:10
I'll close this for now. If it turns out that it's not an issue with performant, feel free to reopen it.

**Closed by noeppi-noeppi** 2021-05-10 07:10 UTC
Labels: question
