### ISSUE TITLE
Server wont load

### ISSUE THREAD

**Issue by willtarax** [noeppi-noeppi/MythicBotany#78] opened 2021-09-08 16:08 UTC
Installed the latest version of MythicBotany (1.4.4) and got server wouldnt load, this line of code is where I started seeing issues with the log.
[08Sep2021 15:54:27.233] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at mythicbotany.alfheim.AlfheimBiomeManager.lambda$checkBiomes$0(AlfheimBiomeManager.java:47)
[debug-1.log](https://github.com/noeppi-noeppi/MythicBotany/files/7130282/debug-1.log)

**Comment by MelanX** [comment] 2021-09-08 16:18
Forge: 36.2.4

**Comment by willtarax** [comment] 2021-09-08 17:03
Is... Is that just additional information? Or is this saying that the error is because I am running on 36.2.4?

**Comment by MelanX** [comment] 2021-09-08 17:13
Additional information for noeppi, so he doesn't need to search for the correct version in your log.

**Comment by noeppi-noeppi** [comment] 2021-09-08 17:21
@MelanX Actually I'm fine with not having the forge version in the issue, as most of the time it does not really matter. And when I create issues and have to fill out a ton of fields it annoys me sometimes. If I later need the forge version, I can still ask back or look into the log.

**Comment by noeppi-noeppi** [comment] 2021-09-08 17:22
Also this is a duplicate of #77

**Closed** 2021-09-08 17:22 UTC
Labels: duplicate
