### ISSUE TITLE
Opening Lexica Botania page of Blood of Kvasir crashes the game

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#50] opened 2021-05-08 18:06 UTC
Title says it all.
The same also happens when you open the Mead of Kvasir in the Lexica Botania and click to the next page.
Probably related to https://github.com/noeppi-noeppi/MythicBotany/issues/48 but the crash log says something different in the description part of the log so it could be another issue.

Crash Log: https://gist.github.com/Wxrlds/eb2fcf75ffe2366840a5ff5a00753a25
![grafik](https://user-images.githubusercontent.com/42120270/117548962-101e2400-b038-11eb-8e9b-23fc58c97f30.png)

**Comment by noeppi-noeppi** [comment] 2021-05-08 18:07
Probably a duplicate of #48

**Closed by noeppi-noeppi** 2021-05-08 18:07 UTC
Labels: duplicate
