### ISSUE TITLE
Mjolnir disappearing upon returning to user. (Requires Apotheosis to recreate)

### ISSUE THREAD

**Issue by CryogenicFrost** [noeppi-noeppi/MythicBotany#84] opened 2021-09-23 19:15 UTC
I noticed a comment on the curseforge page about their Mjolnir disappearing and I also had the same issue. 
![image](https://user-images.githubusercontent.com/13767420/134569668-93e32007-4ef6-4bd0-a77e-7747bfc6460f.png)

I recreated the hammer in creative and have found this. Loyalty 1-3 are vanilla enchantments and do work as intended. Loyalty 4 does return faster and is a little unstable. Loyalty 5+ is uncontrollable and may send the hammer more than 1000 blocks away from the user.

Steps to recreate:
1. Obtain non-vanilla Loyalty levels(4+)
2. Enchant the Mjolnir with the illegal enchantment
3. Throw the hammer
4. Move a distance lateral to where the hammer is after the hammer starts returning to you and allow the homing to undershoot.

My suggestion to amend this problem is to cap the velocity or acceleration of the hammer to prevent unnatural speeds.

Thank you for your time and effort spent into creating this mod.

**Comment by noeppi-noeppi** [comment] 2021-09-23 19:18
Duplicate of #81

**Closed by noeppi-noeppi** 2021-09-23 19:18 UTC
Labels: duplicate
