### ISSUE TITLE
Raindeletia not producing mana

### ISSUE THREAD

**Issue by JeffsRealm** [noeppi-noeppi/MythicBotany#38] opened 2021-04-19 21:49 UTC
Hi so I am playing the Latest Direwolf 20 pack 1.16 1.9.0  
MythicBotany-1.16.3-1.2.10.jar

I just got to the point to produce some Raindeltia and the are not working or working as expected.

So I just created 2 of them and planted them, they bound to the elvish mana spreader there automatically as expected.  Then went on my merry way until it rained I decided to check and see what kind of mana they were producing. I expected them to produce mana passively when raining, then more during thunder storms.

Quick Screenshot of my set up. They both have clear view of the sky and rain. 
![2021-04-19_17 07 47](https://user-images.githubusercontent.com/25747811/115307461-3aff1180-a137-11eb-9d11-ed1b96435ed3.png)

However, no mana was being produced, I watched it for a while and nothing ever happened the spreader never fired.

I did go back later during a thunder storm and it was producing mana during a thunderstorm, but not during just regular rain. From the description I would expect it to generate anytime it rains.  But more when thunder

**Comment by DevilJueChen** [comment] 2021-04-20 04:31
I am a passerby and just happened to see your question.
Planting directly on the grass will not produce mana.
Planting directly on the soil can produce mana.
Planting directly on fresh grass can produce mana.
You can solve the problem briefly and wait for the author to fix it.

**Comment by noeppi-noeppi** [comment] 2021-04-20 14:45
This is intended. To make it produce mana during normal rain plant it on vivid grass. I'll make this clear in the lexicon.

**Comment by thelapisfox** [comment] 2021-04-21 04:28
I planted it on vivid grass and still not getting any mana being produced during rain.

**Comment by noeppi-noeppi** [comment] 2021-04-28 16:53
Not reproducible. It produces only small amounts of mana. Please check you've wired everything correctly and post a screenshot of you setup.

**Comment by noeppi-noeppi** [comment] 2021-05-10 07:11
I'll close this for now as there has been no reply for 12 days. If the problem persists you can reopen the issue and send the screenshot.

**Closed by noeppi-noeppi** 2021-05-10 07:11 UTC
Labels: question
