### ISSUE TITLE
alfheim dimension crashing my server when going through the portal

### ISSUE THREAD

**Issue by asmulf** [noeppi-noeppi/MythicBotany#101] opened 2022-04-13 01:40 UTC
me and my friends have a server and when ever we go through the portal it just crashes the server. i got in contact with the server providers and there saying its something to do with the mod not the server. so any ideas ?

**Comment by noeppi-noeppi** [comment] 2022-04-13 07:21
What version are you using? And please send a log. See https://git.io/mclogs

**Comment by asmulf** [comment] 2022-04-13 17:55
https://paste.ee/p/z71tG here are the logs and im on version 1.18.1

**Comment by noeppi-noeppi** [comment] 2022-04-13 18:16
Duplicate of #96, fixed in 1.18.2

**Closed by noeppi-noeppi** 2022-04-13 18:16 UTC
