### ISSUE TITLE
Mjolnir + Apotheosis Reforging = Bricked World or Crash

### ISSUE THREAD

**Issue by sharkweekthings** [noeppi-noeppi/MythicBotany#131] opened 2023-10-31 14:20 UTC
so I am not sure if this should be reported Apotheosis side, or MythicBotany side, but I'll do both just incase. 

When using MythicBotany-1.19.2-3.0.2 and Apotheosis-1.19.2-6.4.0.jar -- attempting to Reforge Mjolnir to anything (the crash logs use dust + godforged gem in the reforger) causes a crash when attempting to hover over the "results" portion of the Reforging Table.

Am able to reproduce this consistently, and it seems like it may be any affix attempted to be added to Mjolnir causes this problem.

If you happen to get a Mjolnir that also happens to roll an Apotheosis state, your world becomes bricked unless you know how to edit NBT data to remove the item from the data file. This happened to a player who is playing my Modpack. 

[crash-2023-10-30_18.15.50-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/13217479/crash-2023-10-30_18.15.50-client.txt)
[crash-2023-10-31_06.44.27-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/13217480/crash-2023-10-31_06.44.27-client.txt)

Also reported on Apotheosis Discord:
https://discord.com/channels/613010559532531713/613013428621017089/1168917304239730790

**Comment by noeppi-noeppi** [comment] 2023-10-31 16:25
Seems to be a duplicate of #122. #122 was closed because the referenced issue (https://github.com/Shadows-of-Fire/Apotheosis/issues/929) was said to be fixed in 1.19. Therefore I am going to reopen #122 and close this one.

**Closed by noeppi-noeppi** 2023-10-31 16:25 UTC
