### ISSUE TITLE
Alf shatterer won't mine blocks

### ISSUE THREAD

**Issue by Orbsolote** [noeppi-noeppi/MythicBotany#9] opened 2020-11-12 00:45 UTC
Whenever I wear something from alfsteel upgrade (greatest ring of aura or alfsteel complete armor set) and it's supposed to regen my mana it won't let me fully mine any blocks. I think it's maybe stuck repairing it because in normal botany when the pickaxe is being repaired by the band of mana I had the same issue. Any suggestions?

**Comment by Nagispace** [comment] 2020-11-12 07:41
Should be fixed in latest version.

**Comment by noeppi-noeppi** [comment] 2020-11-12 16:31
Duplicate of #8

**Closed by noeppi-noeppi** 2020-11-12 16:31 UTC
Labels: duplicate
